### ISSUE TITLE
javascript:alert('😼')

### ISSUE THREAD

**Issue by bermanboris** [nelsontky/gh-pages-url-shortener-db#18]
XSS on https://nlsn.cf/18

**Comment by nelsontky** [comment]
Damn and I just took a mod about web security.. I should be ashamed :')

**Comment by smac89** [comment]
Another one here:
https://github.com/nelsontky/gh-pages-url-shortener-db/issues/20

**Comment by nelsontky** [comment]
oof thanks for the heads up I may have introduced a regression somewhere :')
